name: API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  openapi-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run test suite
        run: |
          docker compose up --build --abort-on-container-exit

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: schemathesis-report
          path: ./reports/ci-report.xml